new ver 4.5

diff --git a/bin/kibana b/bin/kibana
--- a/bin/kibana
+++ b/bin/kibana
@@ -13,9 +13,12 @@ while [ -h "$SCRIPT" ] ; do
   fi
 done
 
-DIR=$(dirname "${SCRIPT}")/..
-NODE=/usr/local/bin/node
-SERVER=${DIR}/src/bin/kibana.js
+DIR="$(dirname "${SCRIPT}")/.."
+NODE="${DIR}/node/bin/node"
+test -x "$NODE" || NODE=$(which node)
+if [ ! -x "$NODE" ]; then
+  echo "unable to find usable node.js executable."
+  exit 1
+fi
 
-CONFIG_PATH="${DIR}/config/kibana.yml" NODE_ENV="production" exec "${NODE}" ${SERVER} ${@}
-
+exec "${NODE}" $NODE_OPTIONS "${DIR}/src/cli" ${@}
